//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<double> PosX { get; set; }
        public Nullable<double> PosY { get; set; }
        public Nullable<double> PosZ { get; set; }
        public Nullable<int> Vida { get; set; }
        public Nullable<int> Mana { get; set; }
        public int ID_USER_PLAYERS { get; set; }
    
        public virtual User User { get; set; }
    }
}
