//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<double> PosX { get; set; }
        public Nullable<double> PosY { get; set; }
        public Nullable<double> PosZ { get; set; }
        public Nullable<double> Vida { get; set; }
        public Nullable<double> Mana { get; set; }
        public int ID_USER_PLAYERS { get; set; }
        public string Sexo { get; set; }
        public Nullable<double> valorvermelhoblusamasc { get; set; }
        public Nullable<double> valorverdeblusamasc { get; set; }
        public Nullable<double> valorazulblusamasc { get; set; }
        public Nullable<double> valorvermelhocalcamasc { get; set; }
        public Nullable<double> valorverdecalcamasc { get; set; }
        public Nullable<double> valorazulcalcamasc { get; set; }
        public Nullable<int> valorvermelhopelemasc { get; set; }
        public Nullable<int> valorverdepelemasc { get; set; }
        public Nullable<int> valorazulpelemasc { get; set; }
        public Nullable<int> valorvermelhocabelomasc { get; set; }
        public Nullable<int> valorverdecabelomasc { get; set; }
        public Nullable<int> valorazulcabelomasc { get; set; }
        public Nullable<int> Nivel { get; set; }
    
        public virtual User User { get; set; }
    }
}
